version: '3.8'

services:
  db:
    image: postgres:14  
    container_name: postgres_db  
    environment:
      POSTGRES_USER: myuser  
      POSTGRES_PASSWORD: mypassword  
      POSTGRES_DB: pokerecord  
    ports:
      - "5432:5432"  
    volumes:
      - /c/Users/seba/OneDrive/Desktop/r/vol/var/lib/postgresql/data  


